version: "3.8"

services:
    mongo:
        image: mongo:3.4
        ports:
            - "27017:27017"
    derby:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 8000:3456
        network_mode: host
        volumes:
            - ./:/derby_project
            - /derby_project/node_modules
        depends_on: 
            - mongo
